# Generated by Django 5.2.3 on 2025-07-01 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="pin",
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
